version: "3.7"
services:
  asset-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - redis
      - mysql
  redis:
    image: redis:6-alpine3.14
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0.27
    cap_add:
      - SYS_NICE
    volumes:
      - type: volume
        source: mysql-per-volume
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=asset-app
      - MYSQL_PASSWORD=password
      - MYSQL_DB=asset_db
    ports:
      - "3306:3306"
volumes:
  mysql-per-volume: